server:
  port: '${PORT:8080}'
spring:
  cloud:
    gcp:
      datastore:
        project-id: cykt-399216
        credentials:
          location: classpath:chemin/vers/votre/fichier-de-credentials.json

